#!/usr/bin/env bash
# GRUB rescue entry.
#
# Adds a "console (TTY)" entry to the boot menu that starts multi-user.target
# instead of graphical.target, so a broken display manager or compositor never
# locks you out of your own machine. Without it the only way back is editing the
# kernel line from GRUB by hand on every single boot.
#
# It is written to /boot/grub/custom.cfg rather than /etc/grub.d/40_custom
# because Arch's /etc/grub.d/41_custom already makes grub.cfg source that file
# at boot:
#
#   if [ -f ${config_directory}/custom.cfg ]; then source ...
#
# which means the entry needs no `grub-mkconfig` run to appear, and — more
# importantly — survives every future one, since grub-mkconfig only rewrites
# grub.cfg and never touches custom.cfg.
#
# The entry is cloned from the real 'Arch Linux' entry in grub.cfg rather than
# written from scratch. That keeps the root UUID, the ESP search line, the
# kernel/initrd paths and the microcode images correct on any machine, with no
# hardcoded values to drift.
#
# Usage:
#   setup grub rescue    Write (or refresh) the console entry
#   setup grub status    Show what is currently installed
#   setup grub remove    Delete the entry

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
source "$DOTFILES_DIR/cmd/lib/utils.sh"

GRUB_CFG="/boot/grub/grub.cfg"
CUSTOM_CFG="/boot/grub/custom.cfg"
ENTRY_TITLE="Arch Linux (console / TTY)"

# The unit to boot into. multi-user.target is the full system minus the
# graphical session: networking, sshd and all the TTYs, no display manager.
RESCUE_UNIT="multi-user.target"

_require_grub() {
    [[ -f "$GRUB_CFG" ]] || {
        error "Not found: $GRUB_CFG"
        error "This machine does not look like it boots with GRUB."
        exit 1
    }
    if ! grep -q 'custom\.cfg' "$GRUB_CFG"; then
        warn "$GRUB_CFG does not source custom.cfg."
        warn "Run 'sudo grub-mkconfig -o $GRUB_CFG' once, then try again."
        exit 1
    fi
}

# Emit the rescue entry on stdout, derived from the first 'Arch Linux' entry.
_build_entry() {
    local block
    block="$(awk "/^menuentry 'Arch Linux'/,/^}/" "$GRUB_CFG")"
    [[ -n "$block" ]] || { error "No 'Arch Linux' entry found in $GRUB_CFG"; exit 1; }

    echo "# Generated by 'setup grub rescue'. Safe from grub-mkconfig."
    echo "# Regenerate after a kernel or bootloader layout change."
    echo "$block" | awk -v title="$ENTRY_TITLE" -v unit="$RESCUE_UNIT" '
        # Retitle, and drop $menuentry_id_option: reusing the original id would
        # give two entries the same identifier, which breaks GRUB_DEFAULT=saved.
        /^menuentry / {
            print "menuentry \x27" title "\x27 --class arch --class gnu-linux --class gnu --class os {"
            next
        }
        # Boot to the rescue unit, and drop quiet/loglevel so failures are
        # visible — the whole point of this entry is seeing what went wrong.
        /^[[:space:]]*linux[[:space:]]/ {
            gsub(/ quiet/, "")
            gsub(/ loglevel=[0-9]+/, "")
            print $0 " systemd.unit=" unit
            next
        }
        { print }
    '
}

cmd_rescue() {
    prevent_root
    _require_grub

    local tmp
    tmp="$(mktemp)"
    _build_entry >"$tmp"

    info "Entry to install:"
    sed 's/^/      /' "$tmp"
    echo

    sudo install -m 0644 "$tmp" "$CUSTOM_CFG"
    rm -f "$tmp"

    success "Written to $CUSTOM_CFG"
    info "It appears at the bottom of the GRUB menu on the next boot."
    info "No grub-mkconfig needed — grub.cfg already sources this file."
}

cmd_status() {
    _require_grub
    echo
    if [[ -f "$CUSTOM_CFG" ]]; then
        success "$CUSTOM_CFG exists:"
        sed 's/^/      /' "$CUSTOM_CFG"
    else
        warn "No $CUSTOM_CFG — there is no console entry in the boot menu."
        warn "Run 'setup grub rescue' to add one."
    fi
    echo
}

cmd_remove() {
    prevent_root
    if [[ -f "$CUSTOM_CFG" ]]; then
        sudo rm -f "$CUSTOM_CFG"
        success "Removed $CUSTOM_CFG"
    else
        info "Nothing to remove."
    fi
}

_usage() {
    cat <<EOF

Usage: setup grub <subcommand>

    rescue    Add a "console (TTY)" entry that boots $RESCUE_UNIT
    status    Show the currently installed entry
    remove    Delete the entry

The entry exists so a broken greeter or compositor cannot lock you out: pick it
at the GRUB menu, log in on a TTY, fix whatever is wrong.

EOF
}

case "${1:-}" in
    rescue) shift; cmd_rescue "$@" ;;
    status) shift; cmd_status "$@" ;;
    remove) shift; cmd_remove "$@" ;;
    -h|--help|help|"") _usage ;;
    *) error "Unknown subcommand: $1"; _usage; exit 1 ;;
esac
